mimir:
  structuredConfig:

    multitenancy_enabled: true

    common: 
      storage: 
        backend: azure 
        azure: 
          account_name: "storagelgtmlaurajaq" 
          account_key: "7TsC+maT5SNn3BEJS9SkukAEDNlnruO60Ij0CC7Q6c/wrgWE+KTFE6e6E6OkKzrkdsyLlF0nl2cE+AStfswdig=="

    blocks_storage:
      azure:
        container_name: "mimir-blocks"

    ruler_storage:
      azure:
        container_name: "mimir-ruler"

    alertmanager_storage:
      azure:
        container_name: "mimir-alertmanager"

    limits:
      compactor_blocks_retention_period: 30d

# -----------------------------
# Distributor
# -----------------------------
distributor:
  replicas: 2

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi


# -----------------------------
# Ingester
# -----------------------------
ingester:
  replicas: 3

  persistentVolume:
    enabled: true
    size: 10Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi


# -----------------------------
# Querier
# -----------------------------
querier:
  replicas: 2

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi


# -----------------------------
# Query Frontend
# -----------------------------
query_frontend:
  replicas: 2

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi


# -----------------------------
# Query Scheduler
# -----------------------------
query_scheduler:
  replicas: 2


# -----------------------------
# Store Gateway
# -----------------------------
store_gateway:
  replicas: 2

  persistentVolume:
    enabled: true
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi


# -----------------------------
# Compactor
# -----------------------------
compactor:
  replicas: 1

  persistentVolume:
    enabled: true
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi


# -----------------------------
# Ruler
# -----------------------------
ruler:
  replicas: 1


# -----------------------------
# Alertmanager
# -----------------------------
alertmanager:
  replicas: 1

  persistentVolume:
    enabled: true
    size: 5Gi


# -----------------------------
# Mimir Gateway
# -----------------------------
gateway:
  enabled: true

  replicas: 2

  service:
    type: ClusterIP