grafana:
  adminUser: admin
  adminPassword: admin123

  service:
    type: ClusterIP

  grafana.ini:
    server:
      root_url: http://70.153.60.84/grafana
      serve_from_sub_path: true

alertmanager:
  enabled: true

prometheus:
  service:
    type: ClusterIP

  prometheusSpec:
    externalUrl: http://70.153.60.84/prometheus

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false
